name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t wpalmeida/conversor-temperatura-app:latest .
      # working-directory: /currencyconverter

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push wpalmeida/conversor-temperatura-app:latest
      # working-directory: /currencyconverter